[project]
name = "nepali-holidays"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "html5lib>=1.1",
    "icalendar>=6.3.1",
    "lxml>=6.0.2",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
