[project]
name = "nepali-holidays"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "icalendar>=6.3.1",
    "keyring>=25.6.0",
    "pandas>=2.3.2",
]
